[opener]
notebook = [{ run = 'euporie-notebook "$@"', block = true }]

[open]
prepend_rules = [{ name = '*.ipynb', use = "notebook" }]

[preview]
image_delay = 0

[plugin]
prepend_previewers = [{ name = "*.md", run = "glow" }]
